export default {
  REWARD: 'reward',
  REDEEM: 'redeem',
  CHECK_IN: 'check-in',
  EMAIL_DATA_POINT: 'data-point-from-email',
  BANK_DATA_POINT: 'data-point-from-bank',
  CONVERSION: 'conversion',
  STAKING: 'staking',
  STAKING_PAYOUT: 'staking_payout',
  CASH_BACK: 'cashback',
  TRANSFER: 'transfer',
  GIFT_CODE: 'giftcode',
  INTEREST: 'interest',
  MAI: 'mai',
  BANK: 'bank',
};
